### ISSUE TITLE
Could not find gpmf-0.1.1.1 on Hackage

### ISSUE THREAD

**Issue by tallakt** [dustin/gopro#16] opened 2022-10-31 14:53 UTC
Following the installation instructions today I got the following error on `stack install`

```sh
_@_:~/gopro$ stack install
Cabal file info not found for gpmf-0.1.1.1, updating
Selected mirror https://hackage.haskell.org/
Downloading timestamp
Waiting to acquire cache lock on /home/_/.stack/pantry/hackage/hackage-security-lock
Acquired cache lock on /home/_/.stack/pantry/hackage/hackage-security-lock
Released cache lock on /home/_/.stack/pantry/hackage/hackage-security-lock
No package index update available and cache up to date
Package index cache populated
Could not find gpmf-0.1.1.1 on Hackage
Perhaps you meant hmp3, html, time, stm, pqc, gd, exif, Hmpf, hpc, or Diff?
```

I installed `stack`from scratch, after also having failed in the same way for package installed `stack`

**Comment by tallakt** [comment] 2022-10-31 15:58
Seems installing your `gpmf`github repo works, but maybe it should also be mentioned in the `README`

**Comment by dustin** [comment] 2022-10-31 22:20
I'm not sure what's going on here.  gpmf is at https://hackage.haskell.org/package/gpmf and I just downloaded 0.1.1.1 and the cabal file looks correct.  I also did a fresh clone and build.

Perhaps something was temporarily broken?

**Comment by dustin** [comment] 2022-11-06 22:39
I'm closing this as can't reproduce.  I can't guess what's going wrong here as it seems to work fine on my machines and I can see this dep upstream.

**Closed by dustin** 2022-11-06 22:39 UTC
